spam = [
    "Why pay more?",
    "Will not believe your eyes",
    "You are a winner!",
    "You have been selected",
    "You're a winner!",
    "You've been selected"
    "Please read",
    "Stop snoring",
    "Act now!",
    "Do it today",
    "Don't delete",
    "Don't hesitate",
    "Get it now",
    "Order now",
    "Order today",
    "Visit our web site",
    "Visit our website",
    "100% Satisfied",
    "One hundred percent guaranteed",
    "4U",
    "50% off",
    "Accept credit cards",
    "Amazing",
    "Best price",
    "Cards accepted",
    "F r e e",
    "Lowest price",
    "Satisfaction guaranteed",
    "This isn't junk",
    "This isn't spam",
    "$$$",
    "100% free",
    "100% Satisfied",
    "4U",
    "50% off",
    "Accept credit cards",
    "Act now!",
    "Additional income",
    "Addresses on CD",
    "Affordable",
    "All natural",
    "All natural",
    "All new",
    "Amazing",
    "Apply now",
    "Apply online",
    "As seen on...",
    "Auto email removal",
    "Avoid bankruptcy",
    "Bargain",
    "Being a member",
    "Beneficiary",
    "Best price",
    "Beverage",
    "Big bucks",
    "Billing address",
    "Billion dollars",
    "Bulk email",
    "Buy direct",
    "Buying judgments",
    "Cable converter",
    "Call free",
    "Call now",
    "Calling Creditors",
    "Cancel at any time",
    "Cannot be combined with any other offer",
    "Can't live without",
    "Cards accepted",
    "Cash bonus",
    "Cashcashcash",
    "Casino",
    "Celebrity",
    "Cents on the dollar",
    "Certified",
    "Cheap",
    "Clearance",
    "Click below",
    "Click here",
    "Click to remove",
    "Collect child support",
    "Compare rates",
    "Compete for your business",
    "Confidentially on all orders",
    "Congratulations",
    "Consolidate debt and credit",
    "Consolidate your debt",
    "Copy accurately",
    "Copy DVDs",
    "Credit bureaus",
    "Cures baldness",
    "Diagnostics",
    "Direct email",
    "Direct marketing",
    "Discount",
    "Do it today",
    "Don't delete",
    "Don't hesitate",
    "Dormant",
    "Double your",
    "Drastically reduced",
    "Earn extra cash",
    "Earn per week",
    "Easy terms",
    "Eliminate bad credit",
    "Eliminate debt",
    "Email harvest",
    "Email marketing",
    "Expect to earn",
    "Explode your business",
    "Extra income",
    "F r e e",
    "Fantastic deal",
    "Fast cash",
    "Fast Viagra delivery",
    "For free",
    "For instant access",
    "For just $___",
    "For Only",
    "Free access",
    "Free cell phone",
    "Free consultation",
    "Free DVD",
    "Free gift",
    "Free grant money",
    "Free hosting",
    "Free installation",
    "Free and instant",
    "Free investment",
    "Free leads",
    "Free membership",
    "Free money",
    "Free offer",
    "Free preview",
    "Free priority mail",
    "Free quote",
    "Free sample",
    "Free trial",
    "Free website",
    "Freedom",
    "Full refund",
    "Get it now",
    "Get out of debt",
    "Get paid",
    "Get started now",
    "Gift certificate",
    "Give it away",
    "Giving it away",
    "Giving away",
    "Great offer",
    "Have you been turned down?",
    "Hidden assets",
    "Hidden charges",
    "Home employment",
    "Human growth hormone",
    "If only it were that easy",
    "Important information regarding",
    "In accordance with laws",
    "Income from home",
    "Increase sales",
    "Increase traffic",
    "Increase your sales",
    "Incredible deal",
    "Info you requested",
    "Information you requested",
    "Internet marketing",
    "Investment decision",
    "It's effective",
    "Join millions",
    "Legal",
    "Life Insurance",
    "Limited time",
    "Loans",
    "Long distance phone offer",
    "Lose weight",
    "Lower interest rate",
    "Lower monthly payment",
    "Lower your mortgage rate",
    "Lowest insurance rates",
    "Lowest price",
    "Luxury car",
    "Mail in order form",
    "Maintained",
    "Make money",
    "Marketing solutions",
    "Mass email",
    "Medicine",
    "Meet singles",
    "Message contains",
    "Million dollars",
    "Miracle",
    "MLM",
    "Money back",
    "Money making",
    "More internet traffic",
    "Mortgage rates",
    "Multi level marketing",
    "Name brand",
    "New customers only",
    "New domain extensions",
    "Nigerian",
    "No age restrictions",
    "No catch",
    "No claim forms",
    "No cost",
    "No fees",
    "No credit check",
    "No disappointment",
    "No experience",
    "No fees",
    "No gimmick",
    "No hidden costs",
    "No inventory",
    "No investment",
    "No medical exams",
    "No middleman",
    "No obligation",
    "No purchase necessary",
    "No questions asked",
    "No selling",
    "No strings attached",
    "No-obligation",
    "Not intended",
    "Notspam",
    "Now",
    "Now only",
    "Obligation",
    "Off shore",
    "Offer expires",
    "Once in lifetime",
    "One hundred percent free",
    "One hundred percent guaranteed",
    "One time mailing",
    "Online biz opportunity",
    "Online degree",
    "Online marketing",
    "Online pharmacy",
    "Open",
    "Opt in",
    "Order",
    "Order now",
    "Order status",
    "Order today",
    "Orders shipped by",
    "Outstanding value",
    "Passwords",
    "Pennies a day",
    "Per day",
    "Per week",
    "Performance",
    "Please read",
    "Potential earnings",
    "Pre-approved",
    "Price",
    "Print form signature",
    "Print out and fax",
    "Priority mail",
    "Prize",
    "Prizes",
    "Problem",
    "Produced and sent out",
    "Profits",
    "Promise you",
    "Pure profit",
    "Real thing",
    "Refinance",
    "Refinance home",
    "Removal instructions",
    "Removes wrinkles",
    "Requires initial investment",
    "Reserves the right",
    "Reverses aging",
    "Risk free",
    "Rolex",
    "Satisfaction guaranteed",
    "Save $",
    "Save big money",
    "Save up to",
    "Score with babes",
    "Search engine listings",
    "Search engines",
    "See for yourself",
    "Sense of urgency",
    "Sent in compliance",
    "Serious cash",
    "Shopper",
    "Shopping spree",
    "Sign up free today",
    "Social security number",
    "Special promotion",
    "Stainless steel",
    "Stock alert",
    "Stock disclaimer statement",
    "Stock pick",
    "Stop snoring",
    "Stuff on sale",
    "Subject to credit",
    "Success",
    "Supplies are limited",
    "Take action now",
    "Teen",
    "Terms and conditions",
    "The best rates",
    "The following form",
    "They're just giving it away",
    "This isn't junk",
    "This isn't spam",
    "Thousands",
    "Time limited",
    "Undisclosed recipient",
    "University diplomas",
    "Unlimited",
    "Unsecured credit",
    "Unsecured debt",
    "Unsolicited",
    "Unsubscribe",
    "Urgent",
    "US dollars",
    "Vacation offers",
    "Valium",
    "Viagra",
    "Vicodin",
    "Visit our web site",
    "Visit our website",
    "Warranty",
    "We hate spam",
    "We honor all",
    "Web traffic",
    "Weekend getaway",
    "Weight loss",
    "What are you waiting for?",
    "While supplies last",
    "While you sleep",
    "Who really wins?",
    "Wife",
    "Winning",
    "Won",
    "Work at home",
    "Work from home",
    "Xanax"
]