weasels = [
    'are a number',
    'completely',
    'exceedingly',
    'excellent',
    'experts say',
    'extremely',
    'huge',
    'interestingly',
    'is a number',
    'it is known that',
    'largely',
    'obviously',
    'relatively',
    'remarkably',
    'research shows',
    'several',
    'significantly',
    'studies show',
    'substantially',
    'surprisingly',
    'tiny',
    'usually',
    'various',
    'vast',
    'very',
    'with all due respect'
  ]